### ISSUE TITLE
hadolint-py stopped working on Apple silicon Macs

### ISSUE THREAD

**Issue by skycaptain** [AleksaC/hadolint-py#3]
With v2.11.0 hadolint-py stopped working on Apple silicon Macs. I get the following error:
```plain
[...]
              archive, sha256 = ARCHIVE_SHA256[f"{os}-{arch}"]
                                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
          KeyError: 'darwin-arm64'
          [end of output]
```
There is no arm64 pre-built binary release from the hadolint developers, and it seems there never was one. I suspect that previously the x86_64 binary was used and run with Rosetta2? I assume the breaking change was c5c9e474f76f32c53e3f61252fc64fce3b84ca10.

**Comment by AleksaC** [comment]
Thanks for reporting the issue! Should be fixed now (releases 2.11.0.2 and 2.12.0.2)
